### ISSUE TITLE
AnSo - exercises

### ISSUE THREAD

**Issue by aslebloas** [p0x6/holberton-react-workshop-prework#10]
Name: Anne-Sophie Le Bloas
Slack Name: AnSo
Answers:
1) https://jsfiddle.net/q2t7sfLj/3/
2) https://jsfiddle.net/y4co7k0n/
3) https://jsfiddle.net/z9x127Lm/ (updated)
4) https://jsfiddle.net/8rqL0e31/1/
5) https://jsfiddle.net/wk14zv7t/ (updated)
6) https://jsfiddle.net/4hdjy9zu/
7) https://jsfiddle.net/hcupfzg6/
8) https://jsfiddle.net/0egupdz7/
@p0x6

**Comment by p0x6** [comment]
@AnSo
- for exercise 3, there's a short cut for assigning the `key: value` pairs in the object. please use that instead.

- for exercise 5, `setCohort()` should take in a `Student` instance and set the value of the instance on which `setCohort()`was called to the `cohort` of the `Student` instance passed in.

**Comment by aslebloas** [comment]
Hello @p0x6
I have udpated the links. thank you!

**Comment by p0x6** [comment]
LGTM!
