### ISSUE TITLE
React Prework

### ISSUE THREAD

**Issue by leobyeon** [p0x6/holberton-react-workshop-prework#11]
Name: Leo
Slack Name: @leo
Answers:
1) https://jsfiddle.net/j01fLu2p/
2) https://jsfiddle.net/wxeshpaz/
3) https://jsfiddle.net/98603zv1/
4) https://jsfiddle.net/rsa2v56b/
5) https://jsfiddle.net/0acomqd2/
6) https://jsfiddle.net/5cpm6yfo/
7) https://jsfiddle.net/p8c7z4qt/
8) https://jsfiddle.net/pgm4js58/

@p0x6

**Comment by p0x6** [comment]
@leobyeon for exercise 8, let's not use `concat()`. everything else look good!

**Comment by leobyeon** [comment]
Updated! @p0x6

**Comment by p0x6** [comment]
@leobyeon it looks like that returns 2 arrays instead of 1 unshifted array.

**Comment by leobyeon** [comment]
@p0x6 Oops. Updated again.

**Comment by p0x6** [comment]
@leobyeon LGTM!
