### ISSUE TITLE
Feng - Prework

### ISSUE THREAD

**Issue by Rd-Feng** [p0x6/holberton-react-workshop-prework#12]
Name: Rui Feng
Slack Name: Raymond
Answers:
1) https://jsfiddle.net/raymondlf/8z4wLbms/
2) https://jsfiddle.net/raymondlf/4Lxe9vp0/
3) https://jsfiddle.net/raymondlf/rp5wv9a8/
4) https://jsfiddle.net/raymondlf/k3uoveL1/
5) https://jsfiddle.net/raymondlf/eat0mzo6/
6) https://jsfiddle.net/raymondlf/eg9aj4ok/
7) https://jsfiddle.net/raymondlf/2bsL0gkx/
8) https://jsfiddle.net/raymondlf/xb0gspj7/

**Comment by p0x6** [comment]
@Rd-Feng LGTM!
