### ISSUE TITLE
JOgden Prereq Homework

### ISSUE THREAD

**Issue by jogden4195** [p0x6/holberton-react-workshop-prework#13]
Name: Jenn Ogden
Slack Name: Jogden
Answers:
1.) https://jsfiddle.net/83eLyvua/1/
2.) https://jsfiddle.net/j2cxg6pt/
3.) https://jsfiddle.net/5gdahjoq/
4.) https://jsfiddle.net/dtcajnbe/
5.) https://jsfiddle.net/gszheo1n/
6.) https://jsfiddle.net/h1vjtmoc/
7.) https://jsfiddle.net/z1v6hn5u/
8.) https://jsfiddle.net/5qz16ebw/
@p0x6

**Comment by p0x6** [comment]
@jogden4195 
- for 3, please deconstruct the array instead of assigning `key: value` the way you are doing

rest looks good!

**Comment by jogden4195** [comment]
Fixed it! :D
https://jsfiddle.net/4rnwm5v8/
@p0x6

**Comment by p0x6** [comment]
LGTM!
