### ISSUE TITLE
react_workshop

### ISSUE THREAD

**Issue by arturadamian** [p0x6/holberton-react-workshop-prework#14]
Name: Artur Adamian
Slack Name: Artur Adamian
Answers: 
1) const factorial = integer => integer ? (integer * factorial(integer - 1)) : 1;
2) const isStudent = ({title, cohort}) => (title ==='Student' && \
cohort === 2);
7) const spr = (arr1, arr2) => [...arr1, ...arr2];
8) const t = (array, x,y,z) => [x,y,z, ...array];

**Comment by p0x6** [comment]
please use JSFiddle @arturadamian

**Comment by p0x6** [comment]
duplicates: https://github.com/p0x6/holberton-react-workshop-prework/issues/16
