### ISSUE TITLE
jsfidele_url

### ISSUE THREAD

**Issue by arturadamian** [p0x6/holberton-react-workshop-prework#16]
1) https://jsfiddle.net/9ntj6Lv2/
2) https://jsfiddle.net/1ews96u2/
3) https://jsfiddle.net/1ews96u2/1/
4) https://jsfiddle.net/1ews96u2/2/
5) https://jsfiddle.net/1ews96u2/7/
6) https://jsfiddle.net/zaxnhLg8/
7) https://jsfiddle.net/zaxnhLg8/1/
8) https://jsfiddle.net/zaxnhLg8/3/

**Comment by p0x6** [comment]
@arturadamian 
- for 5, `setCohort` should take in a `Student` class instance and set the cohort of itself to the cohort of the `Student` instance passed in.

**Comment by p0x6** [comment]
refer to: https://github.com/p0x6/holberton-react-workshop-prework/issues/19

**Comment by p0x6** [comment]
LGTM!
