### ISSUE TITLE
Bobby's React prework

### ISSUE THREAD

**Issue by hcheung01** [p0x6/holberton-react-workshop-prework#17]
Name: Heindrick cheung
Slack Name: Heindrick Cheung Batch 6
Answers:
1) https://jsfiddle.net/C0MPL3XM1ND/9jtsc6ax/
2) https://jsfiddle.net/C0MPL3XM1ND/6xntv1qj/2/
3) https://jsfiddle.net/C0MPL3XM1ND/3qobe8fz/5/
4) https://jsfiddle.net/C0MPL3XM1ND/kjup4nbs/
5) https://jsfiddle.net/C0MPL3XM1ND/zvw4j8h2/
6) https://jsfiddle.net/C0MPL3XM1ND/th0d7r6y/
7) https://jsfiddle.net/C0MPL3XM1ND/vfmt5rap/3/
8) https://jsfiddle.net/C0MPL3XM1ND/hy0o5sfb/

@p0x6

**Comment by p0x6** [comment]
@hcheung01 
- for exercise 2, please take another look. please use deconstructing

- for exercise 3, please use the method of deconstructing you used in exercise 2

**Comment by p0x6** [comment]
LGTM!
