### ISSUE TITLE
Answers

### ISSUE THREAD

**Issue by anovacap** [p0x6/holberton-react-workshop-prework#2]
Name: Damon Nyhan
Slack Name: Damon
Answers:
1 - https://jsfiddle.net/anovacap/hrdm8gcn/1/
2 - https://jsfiddle.net/anovacap/hrdm8gcn/27/
3 - https://jsfiddle.net/anovacap/hrdm8gcn/35/
4 - https://jsfiddle.net/anovacap/hrdm8gcn/40/
5 - https://jsfiddle.net/anovacap/hrdm8gcn/48/
6 - https://jsfiddle.net/anovacap/hrdm8gcn/16/
7 - https://jsfiddle.net/anovacap/hrdm8gcn/51/
8 - https://jsfiddle.net/anovacap/hrdm8gcn/53/
@p0x6

**Comment by p0x6** [comment]
@anovacap 

- for exercise 2, please take another look. Although you have a spread, it's definitely not in the right place.

- for exercise 3, please use the method of deconstructing you used in exercise 2 along with the `map` helper

- for exercise 4, please read the directions more carefully. to instantiate the `User` class, you need to pass in a `profile` object that has 2 properties. please refactor.

- for exercise 5, same as above + please write the `setCohort()` function instructed in the instructions.

- for exercise 7, please use the spread operator

- for exercise 8, please use the spread operator

**Comment by anovacap** [comment]
revised
@p0x6

**Comment by p0x6** [comment]
for exercise 8, let's not use `concat()`, the rest looks good! @anovacap

**Comment by anovacap** [comment]
new #8 
8 - https://jsfiddle.net/anovacap/hrdm8gcn/55/
@p0x6 

Thanks Bobby

**Comment by p0x6** [comment]
LGTM!
