### ISSUE TITLE
Brennan Answers

### ISSUE THREAD

**Issue by bdbaraban** [p0x6/holberton-react-workshop-prework#3]
Name: Brennan
Slack Name: Brennan D Baraban
Answers:
1) https://jsfiddle.net/bdbaraban/7Lszmkh9/4/
2) https://jsfiddle.net/bdbaraban/mb413ydh/9/
3) https://jsfiddle.net/bdbaraban/zjukcoda/1/
4) https://jsfiddle.net/bdbaraban/xjb8gqe3/7/
5) https://jsfiddle.net/bdbaraban/wcx76q0p/2/
6) https://jsfiddle.net/bdbaraban/grb5md4f/1/
7) https://jsfiddle.net/bdbaraban/qpbavuft/2/
8) https://jsfiddle.net/bdbaraban/zaLh1p63/2/

@p0x6
Thank you Bobby, looking forward to this workshop!

**Comment by p0x6** [comment]
@bdbaraban LGTM! see you wednesday!
