### ISSUE TITLE
Slap my chicken. Cook me slow.

### ISSUE THREAD

**Issue by byn3** [p0x6/holberton-react-workshop-prework#4]
Name: Bryan Leung
Slack Name: Bryan Leung
Answers:
1) https://jsfiddle.net/1pxqhsdo/
2)https://jsfiddle.net/1pxqhsdo/1/
3)https://jsfiddle.net/1pxqhsdo/2/
4)https://jsfiddle.net/1pxqhsdo/3/
5)https://jsfiddle.net/1pxqhsdo/4/
6)https://jsfiddle.net/1pxqhsdo/5/
7)https://jsfiddle.net/1pxqhsdo/6/
8)https://jsfiddle.net/1pxqhsdo/7/

Holberton ID: 369 if you ever wanna email or double check stuff.
@p0x6

**Comment by p0x6** [comment]
@byn3 

- please read `3) Destructuring and Map() Exercise` more carefully, you did not implement properly. the idea is to convert an array of arrays to an array of objects. you basically just made a copy of the original array.

- for `5) ES6 Classes Exercise` the `setCohort` function should take in a `Student` instance and set that instance's cohort to itself. Please read the instructions more carefully.

- for `6) Rest Operator Exercise` although your function implementation is correct, your function call is not. please fix and comment on what was improper about the function call.

**Comment by byn3** [comment]
Thanks for the quick review. I think I fixed the small mistakes.

3) https://jsfiddle.net/p51uy32a/  
Hahahaha. Opps. Totally misunderstood.
5) https://jsfiddle.net/p51uy32a/1/ 
Opppps again.
6) https://jsfiddle.net/p51uy32a/2/ 
I called it using pluses instead of commas. So basically it was adding it all up then doing a reduce of 1 parameter (the input). I derped.

![DYSLEXIA](https://media1.tenor.com/images/863b56b0d6feee85f392345ad81c1e66/tenor.gif?itemid=13921932)

@p0x6

**Comment by p0x6** [comment]
@byn3 LGTM!
