### ISSUE TITLE
JZhang Answers

### ISSUE THREAD

**Issue by iamzinzi** [p0x6/holberton-react-workshop-prework#6]
Name: Jinji Zhang
Slack Name: Jinji
1) https://jsfiddle.net/iamzinzi/v8bt61zj/4/
2) https://jsfiddle.net/iamzinzi/ba8drvgw/3/
3) https://jsfiddle.net/iamzinzi/b7hars1d/15/ *revised*
4) https://jsfiddle.net/iamzinzi/8e3c4z0y/4/
5) https://jsfiddle.net/iamzinzi/p2ctaqwb/8/
6) https://jsfiddle.net/iamzinzi/qeyhbg8k/6/
7) https://jsfiddle.net/iamzinzi/xkzjvbqr/2/
8) https://jsfiddle.net/iamzinzi/hvkr6z5f/5/

@p0x6

**Comment by p0x6** [comment]
@iamzinzi 

- for exercise 3, please use the deconstructing as well as `map`

otherwise, looks good!

**Comment by iamzinzi** [comment]
Revised #3 to use `map` and deconstruction. Thank you! @p0x6

**Comment by p0x6** [comment]
@iamzinzi Looks good to me!
