### ISSUE TITLE
Holberton School React Workshop Prework

### ISSUE THREAD

**Issue by suhearsawho** [p0x6/holberton-react-workshop-prework#7]
Name: Susan Su
Slack Name: suhearsawho
Answers:
1) https://jsfiddle.net/0yde87ta/1/
2) https://jsfiddle.net/xae24unj/
3) https://jsfiddle.net/thy7pqze/1/
4) https://jsfiddle.net/6bwhngyo/
5) https://jsfiddle.net/6bwhngyo/3/
(Not sure what is causing this discrepancy -> When I run it with Google Chrome's Developer Tools console, I am able to see the different values for cohort depending on when setCohort is called. When I run it with JSFiddle, I only see 7 for all print statements.) 
6) https://jsfiddle.net/jhns179u/
7) https://jsfiddle.net/6qpd8gw1/
8) https://jsfiddle.net/g9hd3uep/1/
Thank you! :)
@p0x6

**Comment by p0x6** [comment]
@suhearsawho LGTM!
