### ISSUE TITLE
workshop-prework-submission

### ISSUE THREAD

**Issue by jsjimenez51** [p0x6/holberton-react-workshop-prework#9]
Name: Josh Jimenez
Slack Name: Josh Jimenez
Answers:

1) [https://jsfiddle.net/Jsjimenez51/rLk14mnf/6/](https://jsfiddle.net/Jsjimenez51/rLk14mnf/6/)
2) [https://jsfiddle.net/Jsjimenez51/wq3sf14k/20/](https://jsfiddle.net/Jsjimenez51/wq3sf14k/20/)
3) [https://jsfiddle.net/Jsjimenez51/43t6fjwk/15/](https://jsfiddle.net/Jsjimenez51/43t6fjwk/15/) (updated)
4) [https://jsfiddle.net/Jsjimenez51/L5aqh431/8/](https://jsfiddle.net/Jsjimenez51/L5aqh431/8/)
5) [https://jsfiddle.net/Jsjimenez51/xhjgw1p3/19/](https://jsfiddle.net/Jsjimenez51/xhjgw1p3/19/) (updated)
6) [https://jsfiddle.net/Jsjimenez51/pr2ea6cb/9/](https://jsfiddle.net/Jsjimenez51/pr2ea6cb/9/)
7) [https://jsfiddle.net/Jsjimenez51/fayuskqc/7/](https://jsfiddle.net/Jsjimenez51/fayuskqc/7/)
8) [https://jsfiddle.net/Jsjimenez51/k03p57bq/9/](https://jsfiddle.net/Jsjimenez51/k03p57bq/9/) (updated)

@p0x6

**Comment by p0x6** [comment]
@jsjimenez51 

- please read `3) Destructuring and Map()` Exercise more carefully, you did not implement properly. the idea is to convert an array of arrays to an array of objects.

- for `5) ES6 Classes Exercise` the `setCohort` function should take in a Student instance and set that instance's cohort to itself. Please read the instructions more carefully.

- for `8) Rest Operator Exercise #2` please dont use the `concat()` function, there's a way of doing it using own the rest operator

**Comment by jsjimenez51** [comment]
@p0x6 Hi I have updated with corrections for 3, 5, & 8

**Comment by p0x6** [comment]
@jsjimenez51 LGTM!
